name: CI/CD

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**.md'
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        java-version: 8
        distribution: 'temurin'
        cache: 'gradle'
    
    - name: Build with Gradle
      run: ./gradlew build
    
    - name: Decode
      if: ${{ success() }} && github.ref == 'refs/heads/master'
      run: |
        echo "${{secrets.SIGNING_SECRET_KEY_RING_FILE}}" > ~/.gradle/sonatype_upload.gpg.b64
        base64 -d ~/.gradle/sonatype_upload.gpg.b64 > ~/.gradle/sonatype_upload.gpg
    
    - name: Publish
      #if: ${{ success() }} && github.ref == 'refs/heads/master'
      run: ./gradlew -i publishToSonatype closeAndReleaseSonatypeStagingRepository -Psigning.keyId=${{secrets.SIGNING_KEY_ID}} -Psigning.password=${{secrets.SIGNING_PASSWORD}} -Psigning.secretKeyRingFile=$(echo ~/.gradle/sonatype_upload.gpg)
      env:
        OSSRH_USERNAME: ${{secrets.OSSRH_USERNAME}}
        OSSRH_PASSWORD: ${{secrets.OSSRH_PASSWORD}}
